spring:
  r2dbc:
    url: r2dbc:h2:file:///./products-h2
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
server:
  port: 8080