MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0001', 19.99, 'Wireless Mouse with ergonomic design', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0002', 499.00, '4K Ultra HD Smart TV, 55 inches', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0003', 79.99, 'Bluetooth Headphones with noise cancellation', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0004', 29.99, 'USB-C Charging Cable, 2m', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0005', 149.99, 'Smart Speaker with voice assistant', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0006', 249.99, 'Gaming Keyboard with RGB lighting', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0007', 89.99, 'Wireless Router, dual-band', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0008', 59.99, 'Portable Power Bank, 10000mAh', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0009', 199.99, 'Smart Watch with fitness tracking', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0010', 99.99, 'Wireless Earbuds with charging case', 'Electronics');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0011', 39.99, 'Non-stick Frying Pan, 12 inches', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0012', 24.99, 'Ceramic Mug Set, 4 pieces', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0013', 149.99, 'Air Fryer, 5.8qt', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0014', 49.99, 'Stainless Steel Cutlery Set, 16 pieces', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0015', 79.99, 'Electric Kettle, 1.7L', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0016', 29.99, 'Glass Food Storage Containers, 3 pieces', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0017', 199.99, 'Robot Vacuum Cleaner', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0018', 34.99, 'Cotton Bed Sheet Set, Queen Size', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0019', 69.99, 'Blender with 600W motor', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0020', 44.99, 'Microwaveable Popcorn Maker', 'Home & Kitchen');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0021', 7.50, 'Pack of 10 Ballpoint Pens, Blue Ink', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0022', 12.99, 'A4 Notebook, 100 pages', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0023', 4.99, 'Set of 12 Colored Pencils', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0024', 9.99, 'Desk Organizer with pen holder', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0025', 6.99, 'Sticky Notes, 500 sheets', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0026', 14.99, 'A5 Planner with yearly calendar', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0027', 3.99, 'Eraser Set, 5 pieces', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0028', 19.99, 'Fountain Pen with ink refill', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0029', 8.99, 'Highlighter Set, 6 colors', 'Stationery');
MERGE INTO product (sku, price, description, category) KEY(sku) VALUES ('SKU0030', 11.99, 'Binder Clips, 50 pieces', 'Stationery');